# Generated by Django 4.2.1 on 2023-05-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugname", models.CharField(max_length=32, verbose_name="药品名称")),
                ("drugjixing", models.CharField(max_length=32, verbose_name="剂型")),
                (
                    "money",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="单价"
                    ),
                ),
                ("number", models.IntegerField(verbose_name="库存数量")),
                ("drugspe", models.CharField(max_length=32, verbose_name="规格")),
                ("produce", models.CharField(max_length=32, verbose_name="生产企业")),
                (
                    "insure",
                    models.SmallIntegerField(
                        choices=[
                            (1, "基本药物保险"),
                            (2, "大病药品保险"),
                            (3, "补充药品保险"),
                            (4, "商业药品保险"),
                        ],
                        default=1,
                        verbose_name="医疗保险类型",
                    ),
                ),
                ("drugrat", models.CharField(max_length=64, verbose_name="批准文号")),
                (
                    "drugant",
                    models.SmallIntegerField(
                        choices=[
                            (1, "非抗菌"),
                            (2, "抗生素"),
                            (3, "抗真菌药物"),
                            (4, "抗病毒药物"),
                            (5, "抗寄生虫药物"),
                            (6, "抗结核药物"),
                            (7, "抗原虫药物"),
                        ],
                        default=1,
                        verbose_name="医疗保险类型",
                    ),
                ),
                ("drugnid", models.CharField(max_length=64, verbose_name="药品类型编码")),
                (
                    "drugkey",
                    models.SmallIntegerField(
                        choices=[(1, "是"), (2, "否")], default=2, verbose_name="重点关注药品"
                    ),
                ),
                (
                    "drugun",
                    models.SmallIntegerField(
                        choices=[(1, "通过"), (2, "未通过")], default=2, verbose_name="一致性评价"
                    ),
                ),
            ],
        ),
    ]
