# Generated by Django 4.2.1 on 2023-05-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drug",
            name="drugcate",
            field=models.CharField(blank=True, max_length=32, verbose_name="分类"),
        ),
    ]
