# Generated by Django 4.2.1 on 2023-05-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_drug_drugcate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drug",
            name="drugcate",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="分类"
            ),
        ),
    ]
