# Generated by Django 4.2.1 on 2023-05-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_work_alter_drug_drugant"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutBound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugname", models.CharField(max_length=32, verbose_name="药品名称")),
                (
                    "outmoney",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="购买总价"
                    ),
                ),
                ("innumber", models.IntegerField(verbose_name="出库数量")),
                ("inouttime", models.DateField(verbose_name="出库时间")),
            ],
        ),
    ]
