# Generated by Django 4.2.1 on 2023-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_outbound"),
    ]

    operations = [
        migrations.CreateModel(
            name="InBound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drugname", models.CharField(max_length=32, verbose_name="药品名称")),
                (
                    "outmoney",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="购买总价"
                    ),
                ),
                ("innumber", models.IntegerField(verbose_name="出库数量")),
                ("inouttime", models.DateField(verbose_name="出库时间")),
            ],
        ),
        migrations.RenameField(
            model_name="outbound", old_name="inouttime", new_name="outtime",
        ),
        migrations.RemoveField(model_name="outbound", name="innumber",),
        migrations.AddField(
            model_name="outbound",
            name="outnumber",
            field=models.IntegerField(blank=True, null=True, verbose_name="出库数量"),
        ),
        migrations.AlterField(
            model_name="outbound",
            name="outmoney",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="售出总价"
            ),
        ),
    ]
