# Generated by Django 4.2.1 on 2023-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_outbound_outtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inbound",
            name="innumber",
            field=models.IntegerField(verbose_name="入库数量"),
        ),
        migrations.AlterField(
            model_name="inbound",
            name="inouttime",
            field=models.DateField(verbose_name="入库时间"),
        ),
    ]
