# Generated by Django 4.2.1 on 2023-05-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_inbound_innumber_alter_inbound_inouttime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inbound", old_name="outmoney", new_name="inmoney",
        ),
    ]
