# Generated by Django 4.2.1 on 2023-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_outmoney_inbound_inmoney"),
    ]

    operations = [
        migrations.RenameModel(old_name="InBound", new_name="Purchase",),
        migrations.RenameModel(old_name="OutBound", new_name="Sold",),
        migrations.RenameField(
            model_name="purchase", old_name="inouttime", new_name="intime",
        ),
    ]
