# Generated by Django 4.2.1 on 2023-05-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_rename_inbound_purchase_rename_outbound_sold_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Purchase",),
    ]
