# Generated by Django 4.2.1 on 2023-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_delete_purchase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chdrug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=32, verbose_name="药品名称")),
                (
                    "out_money",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="售出总价"
                    ),
                ),
                (
                    "out_number",
                    models.IntegerField(blank=True, null=True, verbose_name="出库数量"),
                ),
                (
                    "out_time",
                    models.DateField(blank=True, null=True, verbose_name="出库时间"),
                ),
            ],
        ),
        migrations.DeleteModel(name="Sold",),
    ]
