# Generated by Django 4.2.1 on 2023-05-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.CharField(max_length=32, verbose_name="用户名")),
                ("userpwd", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
