# Generated by Django 4.2.1 on 2023-06-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_rename_userword_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="work",
            name="password",
            field=models.CharField(max_length=256, verbose_name="密码"),
        ),
    ]
