# Generated by Django 4.2.1 on 2023-06-17 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_drugadd"),
    ]

    operations = [
        migrations.RenameModel(old_name="Drugadd", new_name="Add",),
    ]
