# Generated by Django 4.2.1 on 2023-06-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_qing_delete_add"),
    ]

    operations = [
        migrations.DeleteModel(name="Qing",),
    ]
